name: Sample to ingest datasets via a PR process

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  detect-files:
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: metadata/**
          matrix: true
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

  process-files:
    needs: detect-files
    if: needs.detect-files.outputs.matrix != ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{fromJson(needs.detect-files.outputs.matrix)}}
      max-parallel: 3
    steps:
      - uses: actions/checkout@v4

      - name: Validate PR, do a test run against a test datahub
        if: github.event_name == 'pull_request'
        uses: acryldata/datahub-action@v1
        with:
          datahub-server: your-test-server
          datahub-token: your-test-PAT
          command: dataset file --lintCheck -f ${{ github.workspace}}/${{ matrix.file }}

      - name: Load file into DataHub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: acryldata/datahub-action@v1
        with:
          datahub-server: your-server
          datahub-token: your-PAT
          command: dataset sync --to-datahub -f ${{ github.workspace}}/${{ matrix.file }}
